### ISSUE TITLE
rollup-plugin-alias@1.4.0: This module has moved

### ISSUE THREAD

**Issue by forconz** [bozaigao/Taro-demo#4]
npm install 出错了，跑不起来啊

PS D:\Taro-demo> npm install
npm WARN deprecated rollup-plugin-alias@1.4.0: This module has moved and is now available at @rollup/plugin-alias. Please update your dependencies. This version is no longer maintained.
Unhandled rejection Error: ENOSPC: no space left on device, writeype@1.2.0 checking installable status

Unhandled rejection Error: ENOSPC: no space left on device, writeype@1.2.0 checking installable status

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

**Comment by forconz** [comment]
如果用cnpm i，会报下面的错误，如何破？

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed (writeStream "error") (writeStream "error"), GET https://cdn.npm.taobao.org/%40babel/plugin-syntax-async-generators/-/%40babel/plugin-syntax-async-generators-7.7.4.tgz 200 (connected: true, keepalive socket: false, agent status: {"createSocketCount":356,"createSocketErrorCount":0,"closeSocketCount":327,"errorSocketCount":0,"timeoutSocketCount":1,"requestCount":1207,"freeSockets":{"r.npm.taobao.org:443::::::::true::::::::::":10,"registry.npm.taobao.org:443::::::::true::::::::::":3},"sockets":{"cdn.npm.taobao.org:443::::::::true::::::::::":10,"registry.npm.taobao.org:443::::::::true::::::::::":6},"requests":{"cdn.npm.taobao.org:443::::::::true::::::::::":10}}, socketHandledRequests: 1, socketHandledResponses: 1)
headers: {"server":"Tengine","content-type":"application/octet-stream","content-length":"1506","connection":"keep-alive","date":"Tue, 10 Dec 2019 02:27:08 GMT","x-oss-request-id":"5DEF027CB1F7903231447C12","accept-ranges":"bytes","etag":"\"843AAF58E06B7CB275C08B5995CD0851\"","last-modified":"Fri, 22 Nov 2019 23:32:00 GMT","x-oss-object-type":"Normal","x-oss-hash-crc64ecma":"10225766706247814442","x-oss-storage-class":"Standard","cache-control":"max-age=0, s-maxage=86400","content-md5":"hDqvWOBrfLJ1wItZlc0IUQ==","x-oss-server-time":"2","age":"55571","ali-swift-global-savetime":"1574902974","x-cache":"HIT TCP_MEM_HIT dirn:10:163326797","x-swift-savetime":"Tue, 10 Dec 2019 02:27:08 GMT","x-swift-cachetime":"86400","via":"vcache19.cn1884[0,200-0,H], vcache6.cn1884[2,0]","timing-allow-origin":"*","eagleid":"3a31f81a15760003997966420e"}
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at WriteStream.Writable.write (_stream_writable.js:299:11)
    at IncomingMessage.ondata (_stream_readable.js:693:20)
    at IncomingMessage.emit (events.js:197:13)
    at IncomingMessage.Readable.read (_stream_readable.js:491:10)
    at flow (_stream_readable.js:957:34)
    at resume_ (_stream_readable.js:938:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

**Comment by forconz** [comment]
整个目录搜copy，把下面代码注释掉
```
    defineConstants: {},
    // copy: {
    //     patterns: [],
    //     options: {}
    // },
    weapp: {
```
注释掉以后，ValidationError: CopyPlugin Invalid Options的问题就解决了
去npm i
然后再npm run dev:h5，就跑起来了。

如果是npm i后出错的，注释代码了，还需要删除node_modules，再重新 npm i
这个问题解决，是搜到https://taro-club.jd.com/topic/946/npm-run-dev-h5%E6%8A%A5%E9%94%99-validationerror-copyplugin-invalid-options/35
这个链接也有ValidationError: CopyPlugin Invalid Options的问题。

吐槽：搜索功能是假的，其它还没仔细看
